logging:
  level:
    root: INFO
spring:
  jpa:
    debug: true
    database: mysql
    hibernate:
      enable_lazy_load_no_trans: true
      ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/coupons
    username: root
    password: ${SQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

jwtsecret: ${JWT_SECRET}